name: Docker CI with Cortex Security

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Variables globales
  CORTEX_URL: https://api-xsiamnfrsentria.xdr.us.paloaltonetworks.com
  API_ID: ${{ secrets.CORTEX_API_KEY_ID }}
  API_KEY: ${{ secrets.CORTEX_API_KEY }}
  IMAGE_NAME: "voting-app-vote:latest"

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- 1. INSTALAR DEPENDENCIAS SISTEMA ---
      - name: Download Cortex dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhyperscan5 jq

      # --- 2. INSTALAR CORTEX CLI (Lógica idéntica a Azure) ---
      - name: Cortex CLI install
        run: |
          set -e
          set -x
          crtx_resp=$(curl "$(CORTEX_API_URL)/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \
          -H "x-xdr-auth-id: $(CORTEX_API_KEY_ID)" \
          -H "Authorization: $(CORTEX_API_KEY)")

          echo "Respuesta API: $crtx_resp"

          crtx_url=$(echo $crtx_resp | jq -r ".signed_url")
  
          if [ -z "$crtx_url" ] || [ "$crtx_url" = "null" ]; then
            echo "##[error]No se pudo obtener el signed_url."
            exit 1
          fi
  
          curl -o cortexcli $crtx_url
          chmod +x cortexcli
          sudo mv cortexcli /usr/local/bin/cortexcli
          cortexcli --version

      # --- 3. CODE SCAN (Antes del Build) ---
      #- name: Cortex Code Scan
    #    run: |
     #     ./$CRTX_FILENAME \
      #      --api-base-url "$CORTEX_URL" \
       #     --api-key "$API_KEY" \
        #    --api-key-id "$API_ID" \
         #   code scan \
          #  --directory "${{ github.workspace }}" \
           # --repo-id "${{ github.repository }}" \
           # --branch "${{ github.ref_name }}" \
           # --source "GITHUB_ACTIONS" \
           # --create-repo-if-missing

      # --- 4. BUILD DE LA IMAGEN ---
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME ./vote

      # --- 5. IMAGE SCAN (Lógica idéntica a Azure) ---
      - name: Cortex Image Scan
        run: |
          set -e
          set -x
          ls
          docker images
          echo "Scanning image: $IMAGE_NAME"
          sudo ./$CRTX_FILENAME \
            --api-base-url "$CORTEX_URL" \
            --api-key "$API_KEY" \
            --api-key-id "$API_ID" \
            image scan $IMAGE_NAME \
            --verbose
