name: Docker CI with Cortex Security

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Variables globales
  CORTEX_URL: https://api-xsiamnfrsentria.xdr.us.paloaltonetworks.com
  API_ID: ${{ secrets.CORTEX_API_KEY_ID }}
  API_KEY: ${{ secrets.CORTEX_API_KEY }}
  IMAGE_NAME: "voting-app-vote:latest"

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- 1. INSTALAR DEPENDENCIAS SISTEMA ---
      - name: Download Cortex dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhyperscan5 jq

      # --- 2. INSTALAR CORTEX CLI (Lógica idéntica a Azure) ---
      - name: Cortex CLI install
        run: |
          crtx_resp=$(curl -s "$CORTEX_URL/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \
            -H "x-xdr-auth-id: $API_ID" \
            -H "Authorization: $API_KEY") 
            
          if [ $? -ne 0 ] || echo "$crtx_resp" | jq -e '.error_code' > /dev/null; then
            echo "Failed to retrieve CLI download link. Response: $crtx_resp"
            exit 1
          fi

          crtx_url=$(echo $crtx_resp | jq -r ".signed_url")
          crtx_file=$(echo $crtx_resp | jq -r ".file_name")
          
          echo "Downloading $crtx_file from signed URL..."
          curl -sL -o "$crtx_file" "$crtx_url"
          chmod +x "$crtx_file"
          
          # Guardamos el nombre del archivo para los siguientes pasos
          echo "CRTX_FILENAME=$crtx_file" >> $GITHUB_ENV

      # --- 3. CODE SCAN (Antes del Build) ---
      #- name: Cortex Code Scan
    #    run: |
     #     ./$CRTX_FILENAME \
      #      --api-base-url "$CORTEX_URL" \
       #     --api-key "$API_KEY" \
        #    --api-key-id "$API_ID" \
         #   code scan \
          #  --directory "${{ github.workspace }}" \
           # --repo-id "${{ github.repository }}" \
           # --branch "${{ github.ref_name }}" \
           # --source "GITHUB_ACTIONS" \
           # --create-repo-if-missing

      # --- 4. BUILD DE LA IMAGEN ---
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME ./vote

      # --- 5. IMAGE SCAN (Lógica idéntica a Azure) ---
      - name: Cortex Image Scan
        run: |
          set -e
          docker images
          echo "Scanning image: $IMAGE_NAME"
          sudo ./$CRTX_FILENAME \
            --api-base-url "$CORTEX_URL" \
            --api-key "$API_KEY" \
            --api-key-id "$API_ID" \
            image scan $IMAGE_NAME \
            --verbose
