name: Docker CI with Cortex Security

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Variables globales
  CORTEX_URL: https://api-xsiamnfrsentria.xdr.us.paloaltonetworks.com
  API_ID: ${{ secrets.CORTEX_API_KEY_ID }}
  API_KEY: ${{ secrets.CORTEX_API_KEY }}
  DOCKER_USER: leonel01py
  IMAGE_NAME: "result"
  TAG: "latest"

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Cortex dependencie
        run: |
          sudo apt-get update
          sudo apt-get install -y libhyperscan5 jq curl wget

      - name: Cortex CLI install
        run: |          
    
          crtx_resp=$(curl -s -S "${CORTEX_URL}/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \
            -H "x-xdr-auth-id: ${API_ID}" \
            -H "Authorization: ${API_KEY}")
          
          crtx_url=$(echo "$crtx_resp" | jq -e -r '.signed_url // empty')

          if [ -z "$crtx_url" ] || [ "$crtx_url" = "null" ]; then
            echo "::error::No se pudo obtener el signed_url de Cortex. Respuesta: $crtx_resp"
            exit 1
          fi

          curl -sL -o cortexcli "$crtx_url"
          chmod +x cortexcli
          mv cortexcli /usr/local/bin/cortexcli

      # --- 3. CODE SCAN (Antes del Build) ---
      #- name: Cortex Code Scan
      #  run: |
       #   cortexcli \
        #    --api-base-url "$CORTEX_URL" \
         #   --api-key "$API_KEY" \
          #  --api-key-id "$API_ID" \
           # code scan \
            #--directory "${{ github.workspace }}" \
            #--repo-id "${{ github.repository }}" \
            #--branch "${{ github.ref_name }}" \
            #--source "GITHUB_ACTIONS" \
            #--create-repo-if-missing

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_USER/$IMAGE_NAME:$TAG ./result

      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1.5
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: leonel01py/result:latest

      - name: Cortex Image Scan
        run: |
          cortexcli \
            --api-base-url "$CORTEX_URL" \
            --api-key "$API_KEY" \
            --api-key-id "$API_ID" \
            image scan $DOCKER_USER/$IMAGE_NAME:$TAG
            
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: leonel01py
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Docker Hub
        run: |
          docker push $DOCKER_USER/$IMAGE_NAME:$TAG
